# Generated by Django 4.2.1 on 2023-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя компании')),
                ('textPost', models.TextField(verbose_name='Описание компании')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
