# Generated by Django 4.2.1 on 2023-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOsnovnPlusNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='chairts',
            field=models.TextField(default=' ', verbose_name='Характеристики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.TextField(default=None, verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
